export enum Genres {
  'Horror',
  'Romance',
  'Science Fiction',
  'Fantasy',
  'Mystery/Suspense',
  'Humour',
  'Paranormal',
  'Adventure',
  'Thriller',
  'Historical Fiction',
  'Teen Fiction',
  'Fan Fiction',
  'Poetry',
  'Short story',
  'Action',
  'Vampire',
  'Werewolf',
  'Spiritual',
  'Non-Fiction',
  'Other'
}
